base = float(input("Digite a base do retângulo: "))
altura = float(input("Digite a altura do retângulo: "))
area = (altura*base)
perimetro = (altura+base)
print ("A área do retângulo é",area,"O perímetro do retângulo é",perimetro)